---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/subskribo.be/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.subskribo.be/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer')"
        AnchorPeers:
            - Host: peer0.org1.subskribo.be
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.subskribo.be:7050
        - orderer1.subskribo.be:8050
        - orderer2.subskribo.be:9050

    EtcdRaft:
        Consenters:
            - Host: orderer0.subskribo.be
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/subskribo.be/orderers/orderer0.subskribo.be/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/subskribo.be/orderers/orderer0.subskribo.be/tls/server.crt
            - Host: orderer1.subskribo.be
              Port: 8050
              ClientTLSCert: crypto-config/ordererOrganizations/subskribo.be/orderers/orderer1.subskribo.be/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/subskribo.be/orderers/orderer1.subskribo.be/tls/server.crt
            - Host: orderer2.subskribo.be
              Port: 9050
              ClientTLSCert: crypto-config/ordererOrganizations/subskribo.be/orderers/orderer2.subskribo.be/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/subskribo.be/orderers/orderer2.subskribo.be/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true
        
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities



Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
            Capabilities:
                <<: *ApplicationCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
