OrdererOrgs:
  - Name: OrdererOrg
    Domain: subskribo.be
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Org1
    Domain: org1.subskribo.be
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
